# Form implementation generated from reading ui file 'add_edit.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddEditDialog(object):
    def setupUi(self, AddEditDialog):
        AddEditDialog.setObjectName("AddEditDialog")
        AddEditDialog.resize(500, 540)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AddEditDialog.sizePolicy().hasHeightForWidth())
        AddEditDialog.setSizePolicy(sizePolicy)
        AddEditDialog.setMinimumSize(QtCore.QSize(500, 540))
        AddEditDialog.setMaximumSize(QtCore.QSize(500, 540))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        AddEditDialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/safekeep_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        AddEditDialog.setWindowIcon(icon)
        AddEditDialog.setStyleSheet("QMainWindow{ \n"
"    background: #0a1931;\n"
"    border-radius: 25px;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    border: 3px solid #0a1931;\n"
"    border-radius: 5px;\n"
"    padding: 10px;\n"
"    color: #0a1931;\n"
"}\n"
"\n"
"QPushButton{\n"
"    border: 3px solid #0a1931;\n"
"    border-radius: 8px;\n"
"    color: #0a1931;\n"
"    padding: 10px;\n"
"\n"
"}\n"
"\n"
"QLabel{\n"
"    \n"
"}\n"
"\n"
"QComboBox{\n"
"    border: 3px solid #0a1931;\n"
"    border-radius: 8px;\n"
"    color: #0a1931;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=AddEditDialog)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frame.setFont(font)
        self.frame.setStyleSheet("QFrame{\n"
"background: #f6fafd;\n"
"border-radius: 30px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.websiteTxt = QtWidgets.QLineEdit(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT")
        font.setPointSize(10)
        self.websiteTxt.setFont(font)
        self.websiteTxt.setStyleSheet("")
        self.websiteTxt.setText("")
        self.websiteTxt.setObjectName("websiteTxt")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.websiteTxt)
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.unameTxt = QtWidgets.QLineEdit(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT")
        font.setPointSize(10)
        self.unameTxt.setFont(font)
        self.unameTxt.setText("")
        self.unameTxt.setObjectName("unameTxt")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.unameTxt)
        self.label_3 = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.emailTxt = QtWidgets.QLineEdit(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT")
        font.setPointSize(10)
        self.emailTxt.setFont(font)
        self.emailTxt.setText("")
        self.emailTxt.setObjectName("emailTxt")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.emailTxt)
        self.label_4 = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.passTxt = QtWidgets.QLineEdit(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT")
        font.setPointSize(10)
        self.passTxt.setFont(font)
        self.passTxt.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.passTxt.setObjectName("passTxt")
        self.horizontalLayout.addWidget(self.passTxt)
        self.showPassBtn = QtWidgets.QPushButton(parent=self.frame)
        self.showPassBtn.setMaximumSize(QtCore.QSize(40, 16777215))
        self.showPassBtn.setStyleSheet("QPushButton::hover{\n"
"    background:     #B3cfe5;\n"
"}")
        self.showPassBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/show.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.showPassBtn.setIcon(icon1)
        self.showPassBtn.setObjectName("showPassBtn")
        self.horizontalLayout.addWidget(self.showPassBtn)
        self.generatePassBtn = QtWidgets.QPushButton(parent=self.frame)
        self.generatePassBtn.setMaximumSize(QtCore.QSize(40, 16777215))
        self.generatePassBtn.setStyleSheet("QPushButton::hover{\n"
"    background:     #B3cfe5;\n"
"}")
        self.generatePassBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/random.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.generatePassBtn.setIcon(icon2)
        self.generatePassBtn.setObjectName("generatePassBtn")
        self.horizontalLayout.addWidget(self.generatePassBtn)
        self.formLayout_2.setLayout(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.horizontalLayout)
        self.label_5 = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_5)
        self.categoryCmb = QtWidgets.QComboBox(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT")
        self.categoryCmb.setFont(font)
        self.categoryCmb.setObjectName("categoryCmb")
        self.categoryCmb.addItem("")
        self.categoryCmb.addItem("")
        self.categoryCmb.addItem("")
        self.categoryCmb.addItem("")
        self.categoryCmb.addItem("")
        self.categoryCmb.addItem("")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.categoryCmb)
        self.gridLayout_2.addLayout(self.formLayout_2, 3, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(30, 30, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout_2.addItem(spacerItem2, 6, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(12, 29, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout_2.addItem(spacerItem3, 2, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(25, 10, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 3, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(25, 10, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 3, 2, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_7 = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("font-size: 20px;\n"
"font-weight: bold;")
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 1, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout_2.addItem(spacerItem6, 0, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem7 = QtWidgets.QSpacerItem(57, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.saveBtn = QtWidgets.QPushButton(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.saveBtn.setFont(font)
        self.saveBtn.setStyleSheet("QPushButton{\n"
"    background: #1a3d63;\n"
"    color: #f6fafd;\n"
"    border-radius: 15px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background: #0a1931;\n"
"}")
        self.saveBtn.setObjectName("saveBtn")
        self.horizontalLayout_2.addWidget(self.saveBtn)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        self.cancelBtn = QtWidgets.QPushButton(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.cancelBtn.setFont(font)
        self.cancelBtn.setStyleSheet("QPushButton{\n"
"    background: #B3cfe5;\n"
"    color: #0a1931;\n"
"    border-radius: 15px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background: #4a7fa7;\n"
"    color: white;\n"
"}")
        self.cancelBtn.setObjectName("cancelBtn")
        self.horizontalLayout_2.addWidget(self.cancelBtn)
        spacerItem9 = QtWidgets.QSpacerItem(75, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem9)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 5, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(50, 6, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem10, 4, 1, 1, 1)
        self.gridLayout.addWidget(self.frame, 1, 1, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem11, 1, 2, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout.addItem(spacerItem12, 2, 1, 1, 1)
        AddEditDialog.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=AddEditDialog)
        self.statusbar.setObjectName("statusbar")
        AddEditDialog.setStatusBar(self.statusbar)

        self.retranslateUi(AddEditDialog)
        self.cancelBtn.pressed.connect(AddEditDialog.close) # type: ignore
        self.showPassBtn.pressed.connect(self.passTxt.show) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AddEditDialog)

    def retranslateUi(self, AddEditDialog):
        _translate = QtCore.QCoreApplication.translate
        AddEditDialog.setWindowTitle(_translate("AddEditDialog", "Add/Edit Password Entry"))
        self.label.setText(_translate("AddEditDialog", "Title:"))
        self.websiteTxt.setPlaceholderText(_translate("AddEditDialog", "E.g. Github"))
        self.label_2.setText(_translate("AddEditDialog", "Username:"))
        self.unameTxt.setPlaceholderText(_translate("AddEditDialog", "user123"))
        self.label_3.setText(_translate("AddEditDialog", "Email:"))
        self.emailTxt.setPlaceholderText(_translate("AddEditDialog", "youremail@email.com"))
        self.label_4.setText(_translate("AddEditDialog", "Password:"))
        self.passTxt.setPlaceholderText(_translate("AddEditDialog", "enter or generate password"))
        self.label_5.setText(_translate("AddEditDialog", "Category:"))
        self.categoryCmb.setItemText(0, _translate("AddEditDialog", "Development"))
        self.categoryCmb.setItemText(1, _translate("AddEditDialog", "Financial"))
        self.categoryCmb.setItemText(2, _translate("AddEditDialog", "School"))
        self.categoryCmb.setItemText(3, _translate("AddEditDialog", "Social"))
        self.categoryCmb.setItemText(4, _translate("AddEditDialog", "Work"))
        self.categoryCmb.setItemText(5, _translate("AddEditDialog", "Others"))
        self.label_7.setText(_translate("AddEditDialog", "Edit Details"))
        self.saveBtn.setText(_translate("AddEditDialog", "Save"))
        self.cancelBtn.setText(_translate("AddEditDialog", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddEditDialog = QtWidgets.QMainWindow()
    ui = Ui_AddEditDialog()
    ui.setupUi(AddEditDialog)
    AddEditDialog.show()
    sys.exit(app.exec())
