# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 750)
        MainWindow.setBaseSize(QtCore.QSize(1200, 700))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT")
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/safekeep_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: #0a1931;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sidebarFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.sidebarFrame.setMaximumSize(QtCore.QSize(250, 16777215))
        self.sidebarFrame.setBaseSize(QtCore.QSize(250, 0))
        self.sidebarFrame.setStyleSheet("QFrame {\n"
"       background-color: #0a1931;\n"
"       border: none;\n"
"       border-right: 2px solid #374151;\n"
"   }")
        self.sidebarFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.sidebarFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.sidebarFrame.setObjectName("sidebarFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.sidebarFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(parent=self.sidebarFrame)
        self.label_2.setMaximumSize(QtCore.QSize(25, 30))
        self.label_2.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border: none;")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("icons/logo.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(parent=self.sidebarFrame)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color:#b3cfe5;\n"
"border: none;")
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.newpassBtn = QtWidgets.QPushButton(parent=self.sidebarFrame)
        self.newpassBtn.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.newpassBtn.setFont(font)
        self.newpassBtn.setStyleSheet("QPushButton {\n"
"         background-color:qlineargradient(spread:pad, x1:0, y1:0.136636, x2:1, y2:1, stop:0 rgba(26, 61, 99, 255), stop:1 rgba(74, 127, 167, 255)) ;\n"
"         color: #f6fafd;\n"
"         border: none;\n"
"         padding: 10px;\n"
"         border-radius: 15px;\n"
"         font-weight: bold;\n"
"     }\n"
"QPushButton:hover {\n"
"         background-color: rgb(108, 159, 193);\n"
"     }")
        self.newpassBtn.setObjectName("newpassBtn")
        self.verticalLayout.addWidget(self.newpassBtn)
        self.categoryList = QtWidgets.QListWidget(parent=self.sidebarFrame)
        self.categoryList.setMinimumSize(QtCore.QSize(0, 300))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT")
        font.setPointSize(10)
        self.categoryList.setFont(font)
        self.categoryList.setStyleSheet("QListWidget {\n"
"         background-color: transparent;\n"
"         border: none;\n"
"         color: #B3cfe5;\n"
"     }\n"
"     QListWidget::item {\n"
"         padding: 12px;\n"
"         border-radius: 5px;\n"
"     }\n"
"     QListWidget::item:selected {\n"
"         background-color: #374151;\n"
"         color: #f3f4f6;\n"
"     }\n"
"     QListWidget::item:hover {\n"
"         background-color: #2d3748;\n"
"     }\n"
"")
        self.categoryList.setObjectName("categoryList")
        item = QtWidgets.QListWidgetItem()
        self.categoryList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.categoryList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.categoryList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.categoryList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.categoryList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.categoryList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.categoryList.addItem(item)
        self.verticalLayout.addWidget(self.categoryList)
        spacerItem1 = QtWidgets.QSpacerItem(27, 200, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.statsLabel = QtWidgets.QLabel(parent=self.sidebarFrame)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT")
        font.setPointSize(8)
        self.statsLabel.setFont(font)
        self.statsLabel.setStyleSheet("QLabel {\n"
"         color: #6b7280;\n"
"         padding: 15px;\n"
"        border: none;\n"
"         border-top: 1px solid #374151;\n"
"        \n"
"     }")
        self.statsLabel.setObjectName("statsLabel")
        self.verticalLayout.addWidget(self.statsLabel)
        self.horizontalLayout.addWidget(self.sidebarFrame)
        self.contentFrame = QtWidgets.QFrame(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT")
        self.contentFrame.setFont(font)
        self.contentFrame.setStyleSheet("QFrame {\n"
"       background-color: #0a1931;\n"
"   }")
        self.contentFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.contentFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.contentFrame.setObjectName("contentFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.contentFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.headerFrame = QtWidgets.QFrame(parent=self.contentFrame)
        self.headerFrame.setStyleSheet("QFrame {\n"
"         background-color: #1f2937;\n"
"         border-bottom: 1px solid #374151;\n"
"     }")
        self.headerFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.headerFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.headerFrame.setObjectName("headerFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.headerFrame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.searchbar = QtWidgets.QLineEdit(parent=self.headerFrame)
        self.searchbar.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT")
        font.setPointSize(10)
        self.searchbar.setFont(font)
        self.searchbar.setStyleSheet("QLineEdit {\n"
"         background-color: #374151;\n"
"         border: 1px solid #4b5563;\n"
"         color: #b3cfe5;\n"
"         padding: 10px;\n"
"         border-radius: 8px;\n"
"     }\n"
"     QLineEdit:focus {\n"
"         border: 2px solid #b3cfe5;\n"
"     }")
        self.searchbar.setText("")
        self.searchbar.setObjectName("searchbar")
        self.horizontalLayout_2.addWidget(self.searchbar)

        self.verticalLayout_2.addWidget(self.headerFrame)
        self.passTable = QtWidgets.QTableWidget(parent=self.contentFrame)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT")
        font.setPointSize(10)
        self.passTable.setFont(font)
        self.passTable.setAutoFillBackground(False)
        self.passTable.setStyleSheet("QTableWidget#passTable {\n"
"    background-color: white;\n"
"    border: 1px solid #d0d0d0;\n"
"    border-radius: 5px;\n"
"    gridline-color: #e0e0e0;\n"
"}\n"
"\n"
"QTableWidget#passTable::item {\n"
"    padding: 8px;\n"
"}\n"
"\n"
"QTableWidget#passTable::item:selected {\n"
"    background-color: #4a90e2;\n"
"    color: white;\n"
"}\n"
"\n"
"QTableWidget#passTable::item:hover {\n"
"    background-color: #e3f2fd;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #1a3d63;\n"
"    color: white;\n"
"    padding: 10px;\n"
"    border: none;\n"
"    font-weight: bold;\n"
"\n"
"}\n"
"\n"
"QHeaderView::section:hover {\n"
"    background-color: #34495e;\n"
"}\n"
"")
        self.passTable.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.passTable.setAlternatingRowColors(True)
        self.passTable.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.passTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.passTable.setObjectName("passTable")
        self.passTable.setColumnCount(5)
        self.passTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        item.setFont(font)
        self.passTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        item.setFont(font)
        self.passTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        item.setFont(font)
        self.passTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        item.setFont(font)
        self.passTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.passTable.setHorizontalHeaderItem(4, item)
        
        # Set responsive column widths - use Stretch for columns that should resize with window
        # Actions column - Fixed width (won't resize)
        self.passTable.setColumnWidth(4, 150)
        self.passTable.horizontalHeader().setSectionResizeMode(4, QtWidgets.QHeaderView.ResizeMode.Fixed)
        
        # Category and Last Modified - Resize to content but with minimum width
        self.passTable.setColumnWidth(2, 120)  # Category - initial width
        self.passTable.setColumnWidth(3, 180)  # Last Modified - initial width
        self.passTable.horizontalHeader().setSectionResizeMode(2, QtWidgets.QHeaderView.ResizeMode.Interactive)
        self.passTable.horizontalHeader().setSectionResizeMode(3, QtWidgets.QHeaderView.ResizeMode.Interactive)
        
        # Website and Username - Stretch to fill remaining space proportionally
        self.passTable.horizontalHeader().setSectionResizeMode(0, QtWidgets.QHeaderView.ResizeMode.Stretch)  # Website
        self.passTable.horizontalHeader().setSectionResizeMode(1, QtWidgets.QHeaderView.ResizeMode.Stretch)  # Username
        
        # Set minimum widths to prevent columns from becoming too narrow
        self.passTable.horizontalHeader().setMinimumSectionSize(100)
        
        # Set minimum row height
        self.passTable.verticalHeader().setDefaultSectionSize(50)
        self.passTable.verticalHeader().setMinimumSectionSize(45)
        
        # Disable stretch last section since we're controlling it manually
        self.passTable.horizontalHeader().setStretchLastSection(False)
        self.passTable.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_2.addWidget(self.passTable)
        self.horizontalLayout.addWidget(self.contentFrame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "SafeKeep"))
        self.newpassBtn.setText(_translate("MainWindow", "+ New Password"))
        __sortingEnabled = self.categoryList.isSortingEnabled()
        self.categoryList.setSortingEnabled(False)
        item = self.categoryList.item(0)
        item.setText(_translate("MainWindow", "All Passwords"))
        item = self.categoryList.item(1)
        item.setText(_translate("MainWindow", "Development"))
        item = self.categoryList.item(2)
        item.setText(_translate("MainWindow", "Financial"))
        item = self.categoryList.item(3)
        item.setText(_translate("MainWindow", "School"))
        item = self.categoryList.item(4)
        item.setText(_translate("MainWindow", "Social"))
        item = self.categoryList.item(5)
        item.setText(_translate("MainWindow", "Work"))
        item = self.categoryList.item(6)
        item.setText(_translate("MainWindow", "Others"))
        self.categoryList.setSortingEnabled(__sortingEnabled)
        self.statsLabel.setText(_translate("MainWindow", "0 passwords stored"))
        self.searchbar.setPlaceholderText(_translate("MainWindow", "Search Passwords"))
        self.passTable.setSortingEnabled(True)
        item = self.passTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Title"))
        item = self.passTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Username"))
        item = self.passTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Category"))
        item = self.passTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Last Modified"))
        item = self.passTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Actions"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
