# Form implementation generated from reading ui file 'master_pass.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_masterPassDialog(object):
    def setupUi(self, masterPassDialog):
        masterPassDialog.setObjectName("masterPassDialog")
        masterPassDialog.resize(500, 540)
        masterPassDialog.setMinimumSize(QtCore.QSize(500, 540))
        masterPassDialog.setMaximumSize(QtCore.QSize(500, 540))
        font = QtGui.QFont()
        font.setPointSize(8)
        masterPassDialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/safekeep_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        masterPassDialog.setWindowIcon(icon)
        masterPassDialog.setStyleSheet("background: #f6fafd;")
        self.centralwidget = QtWidgets.QWidget(parent=masterPassDialog)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout_3.addItem(spacerItem, 2, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout_3.addItem(spacerItem1, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 1, 2, 1, 1)
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setStyleSheet("background: #0a1931;\n"
"border-radius: 25px;\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_12 = QtWidgets.QLabel(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMaximumSize(QtCore.QSize(15, 20))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("icons/logo.png"))
        self.label_12.setScaledContents(True)
        self.label_12.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_12.setWordWrap(False)
        self.label_12.setIndent(0)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_3.addWidget(self.label_12)
        self.label_11 = QtWidgets.QLabel(parent=self.frame)
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("QLabel{\n"
"    color: #B3CFE5;\n"
"}")
        self.label_11.setScaledContents(False)
        self.label_11.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_11.setWordWrap(False)
        self.label_11.setIndent(0)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_3.addWidget(self.label_11)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_13 = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(26)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("QLabel{\n"
"    color: white;\n"
"}")
        self.label_13.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_6.addWidget(self.label_13, 1, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT")
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("QLabel{\n"
"    color: #4A7FA7;\n"
"}")
        self.label_17.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_6.addWidget(self.label_17, 0, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout_6.addItem(spacerItem5, 2, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_6)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem6 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.line = QtWidgets.QFrame(parent=self.frame)
        self.line.setStyleSheet("background: #4A7FA7;\n"
"border: 1px solid #0a1931;")
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_8.addWidget(self.line)
        self.label_16 = QtWidgets.QLabel(parent=self.frame)
        self.label_16.setMaximumSize(QtCore.QSize(30, 35))
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("icons/logo.png"))
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_8.addWidget(self.label_16)
        self.line_2 = QtWidgets.QFrame(parent=self.frame)
        self.line_2.setStyleSheet("background: #4A7FA7;\n"
"border: 1px solid #0a1931;")
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_8.addWidget(self.line_2)
        spacerItem7 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        spacerItem8 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout.addItem(spacerItem8)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_18 = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT")
        font.setPointSize(11)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color: #f6fafd")
        self.label_18.setObjectName("label_18")
        self.gridLayout_5.addWidget(self.label_18, 0, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_5.addItem(spacerItem9, 1, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_5.addItem(spacerItem10, 1, 2, 1, 1)
        self.frame_2 = QtWidgets.QFrame(parent=self.frame)
        self.frame_2.setStyleSheet("QFrame{\n"
"    border: 2px solid #f6fafd;\n"
"    border-radius: 10px;\n"
"    \n"
"    color: #f6fafd\n"
"}\n"
"QFrame::hover{\n"
"    border: 2px solid #B3cfe5;\n"
"}\n"
"QFrame::focus{\n"
"    border: 2px solid #B3cfe5;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.passTxt_2 = QtWidgets.QLineEdit(parent=self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT")
        font.setPointSize(12)
        self.passTxt_2.setFont(font)
        self.passTxt_2.setStyleSheet("background: transparent;\n"
"color: white;\n"
"border: none;\n"
"padding: 0px;\n"
"margin: 0px;")
        self.passTxt_2.setText("")
        self.passTxt_2.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.passTxt_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.passTxt_2.setObjectName("passTxt_2")
        self.horizontalLayout.addWidget(self.passTxt_2)
        self.show_masterPassBtn = QtWidgets.QPushButton(parent=self.frame_2)
        self.show_masterPassBtn.setStyleSheet("QPushButton::hover{\n"
"    background: rgba(74, 127, 167, 0.5);\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton{\n"
"    padding: 5px;\n"
"}")
        self.show_masterPassBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/show_light.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.show_masterPassBtn.setIcon(icon1)
        self.show_masterPassBtn.setIconSize(QtCore.QSize(25, 25))
        self.show_masterPassBtn.setObjectName("show_masterPassBtn")
        self.horizontalLayout.addWidget(self.show_masterPassBtn)
        self.gridLayout_5.addWidget(self.frame_2, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_5)
        spacerItem11 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem11)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem12 = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_4.addItem(spacerItem12, 0, 0, 1, 1)
        self.loginBtn = QtWidgets.QPushButton(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT")
        font.setPointSize(12)
        self.loginBtn.setFont(font)
        self.loginBtn.setStyleSheet("QPushButton{\n"
"    background: #f6fafd;\n"
"    padding: 10px;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton::hover{\n"
"    background: #4a7fa7;\n"
"    color: white;\n"
"}\n"
"\n"
"")
        self.loginBtn.setObjectName("loginBtn")
        self.gridLayout_4.addWidget(self.loginBtn, 0, 1, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_4.addItem(spacerItem13, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_4)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout.addItem(spacerItem14)
        self.gridLayout_3.addWidget(self.frame, 1, 1, 1, 1)
        masterPassDialog.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=masterPassDialog)
        self.statusbar.setObjectName("statusbar")
        masterPassDialog.setStatusBar(self.statusbar)

        self.retranslateUi(masterPassDialog)
        QtCore.QMetaObject.connectSlotsByName(masterPassDialog)

    def retranslateUi(self, masterPassDialog):
        _translate = QtCore.QCoreApplication.translate
        masterPassDialog.setWindowTitle(_translate("masterPassDialog", "Password Manager - Login"))
        self.label_11.setText(_translate("masterPassDialog", "SafeKeep"))
        self.label_13.setText(_translate("masterPassDialog", "Username!"))
        self.label_17.setText(_translate("masterPassDialog", "Welcome back,"))
        self.label_18.setText(_translate("masterPassDialog", "Enter Master Password:"))
        self.loginBtn.setText(_translate("masterPassDialog", "Login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    masterPassDialog = QtWidgets.QMainWindow()
    ui = Ui_masterPassDialog()
    ui.setupUi(masterPassDialog)
    masterPassDialog.show()
    sys.exit(app.exec())
