# Form implementation generated from reading ui file 'sign_up.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModality.NonModal)
        MainWindow.resize(1000, 700)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 700))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/safekeep_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("QMainWindow{\n"
"    padding: 0px;\n"
"    margin: 0px;\n"
"}")
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.welcomeBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.welcomeBox.sizePolicy().hasHeightForWidth())
        self.welcomeBox.setSizePolicy(sizePolicy)
        self.welcomeBox.setStyleSheet("QGroupBox {\n"
"    Background: #0A1931;\n"
"border: none;\n"
"}")
        self.welcomeBox.setTitle("")
        self.welcomeBox.setObjectName("welcomeBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.welcomeBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetNoConstraint)
        self.horizontalLayout_2.setSpacing(7)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.welcomeBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(20, 25))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("icons/logo.png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label.setWordWrap(False)
        self.label.setIndent(0)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(parent=self.welcomeBox)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel{\n"
"    color: #B3CFE5;\n"
"}")
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_2.setWordWrap(False)
        self.label_2.setIndent(0)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(31, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.label_3 = QtWidgets.QLabel(parent=self.welcomeBox)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT")
        font.setPointSize(33)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel{\n"
"    color: #4A7FA7;\n"
"}")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(parent=self.welcomeBox)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(42)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel{\n"
"    color: white;\n"
"}")
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.line = QtWidgets.QFrame(parent=self.welcomeBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.line.setFont(font)
        self.line.setStyleSheet("Line{\n"
"    Background: #4A7FA7;\n"
"}")
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_4.addWidget(self.line)
        self.label_5 = QtWidgets.QLabel(parent=self.welcomeBox)
        self.label_5.setMaximumSize(QtCore.QSize(20, 25))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("icons/logo.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.line_2 = QtWidgets.QFrame(parent=self.welcomeBox)
        self.line_2.setStyleSheet("Line{\n"
"    Background: #4A7FA7;\n"
"}")
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_4.addWidget(self.line_2)
        spacerItem3 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_3.addItem(spacerItem4)
        self.label_6 = QtWidgets.QLabel(parent=self.welcomeBox)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("QLabel{\n"
"    color: #4A7FA7;\n"
"}")
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        spacerItem5 = QtWidgets.QSpacerItem(20, 38, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem5)
        self.horizontalLayout.addWidget(self.welcomeBox)
        self.signupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.signupBox.setStyleSheet("QGroupBox{\n"
"    Background: #F6FAFD;\n"
"border-radius: 0px;\n"
"border: none;\n"
"}")
        self.signupBox.setTitle("")
        self.signupBox.setObjectName("signupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.signupBox)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem6, 0, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem7, 2, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem8, 1, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem9, 1, 2, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(parent=self.signupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(200)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(400, 500))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT")
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("QGroupBox{\n"
"    border: 3px solid rgb(10, 25, 49);\n"
"    border-radius: 30px;\n"
"\n"
"\n"
"}\n"
"\n"
"QLineEdit{\n"
"    border: 3px solid #0A1931;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"}")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout_2.addItem(spacerItem10, 11, 3, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem11 = QtWidgets.QSpacerItem(100, 36, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem11)
        self.signUpBtn = QtWidgets.QPushButton(parent=self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.signUpBtn.setFont(font)
        self.signUpBtn.setStyleSheet("QPushButton{\n"
"    background: qlineargradient(spread:pad, x1:0.562, y1:0.426, x2:1, y2:1, stop:0 rgba(10, 25, 49, 255), stop:1 rgba(0, 85, 255, 255));\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background: #1a3d63;\n"
"}")
        self.signUpBtn.setObjectName("signUpBtn")
        self.horizontalLayout_7.addWidget(self.signUpBtn)
        spacerItem12 = QtWidgets.QSpacerItem(100, 36, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem12)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 10, 2, 1, 2)
        self.frame_2 = QtWidgets.QFrame(parent=self.groupBox)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_2.setStyleSheet("QFrame{\n"
"    padding: 0px;\n"
"    border: 3px solid #0A1931;\n"
"    border-radius: 8px;\n"
"}\n"
"QFrame::focus{\n"
"    border: 3px solid #4a7fa7;\n"
"}\n"
"QFrame::hover{\n"
"    border: 3px solid #4a7fa7;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.confirmPassTxt = QtWidgets.QLineEdit(parent=self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT")
        font.setPointSize(10)
        self.confirmPassTxt.setFont(font)
        self.confirmPassTxt.setStyleSheet("border: none;\n"
"background: transparent;")
        self.confirmPassTxt.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.confirmPassTxt.setObjectName("confirmPassTxt")
        self.horizontalLayout_6.addWidget(self.confirmPassTxt)
        self.showPassBtn_2 = QtWidgets.QPushButton(parent=self.frame_2)
        self.showPassBtn_2.setStyleSheet("QPushButton{\n"
"    Background: transparent;\n"
"    border-radius: 5px;\n"
"    border: none;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton::hover{\n"
"    Background: rgba(74, 127, 167, 0.3);\n"
"}")
        self.showPassBtn_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/show.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.showPassBtn_2.setIcon(icon1)
        self.showPassBtn_2.setObjectName("showPassBtn_2")
        self.horizontalLayout_6.addWidget(self.showPassBtn_2)
        self.gridLayout_2.addWidget(self.frame_2, 8, 2, 1, 2)
        self.frame = QtWidgets.QFrame(parent=self.groupBox)
        self.frame.setMinimumSize(QtCore.QSize(0, 50))
        self.frame.setStyleSheet("QFrame{\n"
"    padding: 0px;\n"
"    border: 3px solid #0A1931;\n"
"    border-radius: 8px;\n"
"}\n"
"QFrame::focus{\n"
"    border: 3px solid #4a7fa7;\n"
"}\n"
"QFrame::hover{\n"
"    border: 3px solid #4a7fa7;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.passTxt = QtWidgets.QLineEdit(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT")
        font.setPointSize(10)
        self.passTxt.setFont(font)
        self.passTxt.setStyleSheet("border: none;\n"
"margin: 0px;\n"
"background: transparent;")
        self.passTxt.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.passTxt.setObjectName("passTxt")
        self.horizontalLayout_5.addWidget(self.passTxt)
        self.showPassBtn = QtWidgets.QPushButton(parent=self.frame)
        self.showPassBtn.setStyleSheet("QPushButton{\n"
"    Background: transparent;\n"
"    border-radius: 8px;\n"
"    border: none;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton::hover{\n"
"    Background: rgba(74, 127, 167, 0.3);\n"
"}")
        self.showPassBtn.setText("")
        self.showPassBtn.setIcon(icon1)
        self.showPassBtn.setObjectName("showPassBtn")
        self.horizontalLayout_5.addWidget(self.showPassBtn)
        self.gridLayout_2.addWidget(self.frame, 6, 2, 1, 2)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout_2.addItem(spacerItem13, 0, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(parent=self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT")
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 5, 2, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem14, 6, 4, 1, 1)
        self.label_9 = QtWidgets.QLabel(parent=self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT")
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 7, 2, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout_2.addItem(spacerItem15, 9, 3, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem16, 6, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(parent=self.groupBox)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_3.setStyleSheet("QFrame{\n"
"    padding: 0px;\n"
"    border: 3px solid #0A1931;\n"
"    border-radius: 8px;\n"
"}\n"
"QFrame::focus{\n"
"    border: 3px solid #4a7fa7;\n"
"}\n"
"QFrame::hover{\n"
"    border: 3px solid #4a7fa7;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.usernameTxt = QtWidgets.QLineEdit(parent=self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT")
        font.setPointSize(10)
        self.usernameTxt.setFont(font)
        self.usernameTxt.setStyleSheet("border: none;\n"
"background: transparent\n"
"")
        self.usernameTxt.setObjectName("usernameTxt")
        self.horizontalLayout_8.addWidget(self.usernameTxt)
        self.gridLayout_2.addWidget(self.frame_3, 4, 2, 1, 2)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout_2.addItem(spacerItem17, 2, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(parent=self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT")
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 3, 2, 1, 2)
        self.label_10 = QtWidgets.QLabel(parent=self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 1, 2, 1, 2)
        self.gridLayout.addWidget(self.groupBox, 1, 1, 1, 1)
        self.horizontalLayout.addWidget(self.signupBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SafeKeep - Password Manager"))
        self.label_2.setText(_translate("MainWindow", "SafeKeep"))
        self.label_3.setText(_translate("MainWindow", "WELCOME TO"))
        self.label_4.setText(_translate("MainWindow", "SafeKeep"))
        self.label_6.setText(_translate("MainWindow", "Password Manager"))
        self.signUpBtn.setText(_translate("MainWindow", "Sign Up"))
        self.label_8.setText(_translate("MainWindow", "Password:"))
        self.label_9.setText(_translate("MainWindow", "Confirm Password:"))
        self.label_7.setText(_translate("MainWindow", "Username:"))
        self.label_10.setText(_translate("MainWindow", "Setup Master Password"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
