# Form implementation generated from reading ui file 'view_details.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Viewdetailsdialog(object):
    def setupUi(self, Viewdetailsdialog):
        Viewdetailsdialog.setObjectName("Viewdetailsdialog")
        Viewdetailsdialog.resize(500, 540)
        Viewdetailsdialog.setMinimumSize(QtCore.QSize(500, 540))
        Viewdetailsdialog.setMaximumSize(QtCore.QSize(500, 540))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        Viewdetailsdialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/safekeep_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Viewdetailsdialog.setWindowIcon(icon)
        Viewdetailsdialog.setStyleSheet("QMainWindow{ \n"
"    background: #0a1931;\n"
"    border-radius: 25px;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    border: 3px solid #0a1931;\n"
"    border-radius: 5px;\n"
"    padding: 10px;\n"
"    color: #0a1931;\n"
"}\n"
"\n"
"QPushButton{\n"
"    border: 3px solid #0a1931;\n"
"    border-radius: 8px;\n"
"    color: #0a1931;\n"
"    padding: 10px;\n"
"\n"
"}\n"
"\n"
"QLabel{\n"
"    \n"
"}\n"
"\n"
"QComboBox{\n"
"    border: 3px solid #0a1931;\n"
"    border-radius: 8px;\n"
"    color: #0a1931;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QTextEdit{\n"
"    border: 3px solid #0a1931;\n"
"    border-radius: 8px;\n"
"    color: #0a1931;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=Viewdetailsdialog)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frame.setFont(font)
        self.frame.setStyleSheet("QFrame{\n"
"background: #f6fafd;\n"
"border-radius: 30px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(260, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.closeBtn = QtWidgets.QPushButton(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.closeBtn.setFont(font)
        self.closeBtn.setStyleSheet("QPushButton{\n"
"    background: #B3cfe5;\n"
"    color: #0a1931;\n"
"    border-radius: 15px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background: #4a7fa7;\n"
"    color: white;\n"
"}")
        self.closeBtn.setObjectName("closeBtn")
        self.horizontalLayout_2.addWidget(self.closeBtn)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 5, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(10, 30, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout_2.addItem(spacerItem3, 0, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(25, 10, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 3, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(10, 30, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout_2.addItem(spacerItem5, 6, 1, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_7 = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("font-size: 20px;\n"
"font-weight: bold;")
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 1, 1, 1, 1)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.unameTxt = QtWidgets.QLineEdit(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT")
        font.setPointSize(10)
        self.unameTxt.setFont(font)
        self.unameTxt.setText("")
        self.unameTxt.setReadOnly(True)
        self.unameTxt.setPlaceholderText("")
        self.unameTxt.setObjectName("unameTxt")
        self.horizontalLayout_6.addWidget(self.unameTxt)
        self.copyUsername = QtWidgets.QPushButton(parent=self.frame)
        self.copyUsername.setMaximumSize(QtCore.QSize(40, 16777215))
        self.copyUsername.setStyleSheet("QPushButton::hover{\n"
"    background:     #B3cfe5;\n"
"}")
        self.copyUsername.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/copy.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.copyUsername.setIcon(icon1)
        self.copyUsername.setObjectName("copyUsername")
        self.horizontalLayout_6.addWidget(self.copyUsername)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.horizontalLayout_6)
        self.label_3 = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.emailTxt = QtWidgets.QLineEdit(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT")
        font.setPointSize(10)
        self.emailTxt.setFont(font)
        self.emailTxt.setText("")
        self.emailTxt.setReadOnly(True)
        self.emailTxt.setPlaceholderText("")
        self.emailTxt.setObjectName("emailTxt")
        self.horizontalLayout_5.addWidget(self.emailTxt)
        self.copyEmail = QtWidgets.QPushButton(parent=self.frame)
        self.copyEmail.setMaximumSize(QtCore.QSize(40, 16777215))
        self.copyEmail.setStyleSheet("QPushButton::hover{\n"
"    background:     #B3cfe5;\n"
"}")
        self.copyEmail.setText("")
        self.copyEmail.setIcon(icon1)
        self.copyEmail.setObjectName("copyEmail")
        self.horizontalLayout_5.addWidget(self.copyEmail)
        self.formLayout_2.setLayout(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.horizontalLayout_5)
        self.label_4 = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.passTxt = QtWidgets.QLineEdit(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT")
        font.setPointSize(10)
        self.passTxt.setFont(font)
        self.passTxt.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.passTxt.setReadOnly(True)
        self.passTxt.setPlaceholderText("")
        self.passTxt.setObjectName("passTxt")
        self.horizontalLayout.addWidget(self.passTxt)
        self.showPassBtn = QtWidgets.QPushButton(parent=self.frame)
        self.showPassBtn.setMaximumSize(QtCore.QSize(40, 16777215))
        self.showPassBtn.setStyleSheet("QPushButton::hover{\n"
"    background:     #B3cfe5;\n"
"\n"
"}")
        self.showPassBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/show.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.showPassBtn.setIcon(icon2)
        self.showPassBtn.setObjectName("showPassBtn")
        self.horizontalLayout.addWidget(self.showPassBtn)
        self.copyPass = QtWidgets.QPushButton(parent=self.frame)
        self.copyPass.setMaximumSize(QtCore.QSize(40, 16777215))
        self.copyPass.setStyleSheet("QPushButton::hover{\n"
"    background:     #B3cfe5;\n"
"}")
        self.copyPass.setText("")
        self.copyPass.setIcon(icon1)
        self.copyPass.setObjectName("copyPass")
        self.horizontalLayout.addWidget(self.copyPass)
        self.formLayout_2.setLayout(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.horizontalLayout)
        self.label_5 = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_5)
        self.categoryTxt = QtWidgets.QLineEdit(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT")
        font.setPointSize(10)
        self.categoryTxt.setFont(font)
        self.categoryTxt.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.categoryTxt.setReadOnly(True)
        self.categoryTxt.setPlaceholderText("")
        self.categoryTxt.setObjectName("categoryTxt")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.categoryTxt)
        self.gridLayout_2.addLayout(self.formLayout_2, 3, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(25, 10, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 3, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(10, 30, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout_2.addItem(spacerItem7, 2, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem8, 4, 1, 1, 1)
        self.gridLayout.addWidget(self.frame, 1, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem9, 1, 2, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout.addItem(spacerItem10, 2, 1, 1, 1)
        Viewdetailsdialog.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=Viewdetailsdialog)
        self.statusbar.setObjectName("statusbar")
        Viewdetailsdialog.setStatusBar(self.statusbar)

        self.retranslateUi(Viewdetailsdialog)
        self.closeBtn.pressed.connect(Viewdetailsdialog.close) # type: ignore
        self.copyPass.pressed.connect(self.passTxt.copy) # type: ignore
        self.copyEmail.pressed.connect(self.emailTxt.copy) # type: ignore
        self.copyUsername.pressed.connect(self.unameTxt.copy) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Viewdetailsdialog)

    def retranslateUi(self, Viewdetailsdialog):
        _translate = QtCore.QCoreApplication.translate
        Viewdetailsdialog.setWindowTitle(_translate("Viewdetailsdialog", "View Details"))
        self.closeBtn.setText(_translate("Viewdetailsdialog", "Close"))
        self.label_7.setText(_translate("Viewdetailsdialog", "Title"))
        self.label_2.setText(_translate("Viewdetailsdialog", "Username:"))
        self.label_3.setText(_translate("Viewdetailsdialog", "Email:"))
        self.label_4.setText(_translate("Viewdetailsdialog", "Password:"))
        self.label_5.setText(_translate("Viewdetailsdialog", "Category:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Viewdetailsdialog = QtWidgets.QMainWindow()
    ui = Ui_Viewdetailsdialog()
    ui.setupUi(Viewdetailsdialog)
    Viewdetailsdialog.show()
    sys.exit(app.exec())
